# Site settings
title: Hello there
mazin:  Nice to meet you
email: hiya@email.com
url: http://127.0.0.1:4000/
description: "Im Amy an IxD Designer from NI."
baseurl: 

# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: 'white'
  links: '#219ab3'

# Footer settings
footer: Designed and Coded by Amy Graham

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: https://twitter.com/SBootstrap
  - title: facebook
    url:
  - title: stack-overflow
    url: http://stackoverflow.com/questions/tagged/jekyll
  - title: bitbucket
    url: http://bitbucket.org/jekyll
  - title: github
    url: https://github.com/IronSummitMedia/startbootstrap

# Build settings
markdown: kramdown
permalink: pretty
